### ISSUE TITLE
[feat]  add custom IPFS gateways

### ISSUE THREAD

**Issue by zu1k** [zlib-searcher/zlib-searcher#38]
By default, zlib-searcher should't provide any IPFS gateway address, and the gateway addressed should be added by the user.

So we should provide the ability to add a custom IPFS gateway address:

- On the browser side, we should store the IPFS gateway addresses added by the user in the local storage of the browser, and read it when displaying the IPFS download buttons.
- On the client side, we should store the IPFS gateway addresses in the configuration file.

By allowing users to add IPFS gateway addresses by themselves, the direct association with the file provider can be cut off, thereby avoiding potential legal risks as much as possible.

**Comment by Wybxc** [comment]
Maybe a more flexible configuation? 

Define templates instead of just gateways, and it will be able to construct something else, such as an `ipget` command line.

**Comment by missuo** [comment]
> On the client side, we should store the IPFS gateway addresses in the configuration file.

@zu1k May I ask how to configure several custom IPFS gateways before the project starts?

**Comment by zu1k** [comment]
> > On the client side, we should store the IPFS gateway addresses in the configuration file.
> 
> @zu1k May I ask how to configure several custom IPFS gateways before the project starts?

No, you can’t. Only users can do this.

**Comment by godlockin** [comment]
maybe the ipget address can be set as a env properties inside the docker image/docker compose file so that customers can set it during the bootstrap?
