### ISSUE TITLE
docker-compose 部署的时候无法拉取镜像

### ISSUE THREAD

**Issue by ZevaXu** [zlib-searcher/zlib-searcher#40]
无法拉取镜像：ghcr.io/zlib-searcher/zlib-searcher:latest

不知道是啥情况

**Comment by zu1k** [comment]
抱歉，仓库迁移导致之前的版本丢失，可以使用master版

**Comment by ZevaXu** [comment]
可以详细说一下吗，目前就是按master分支下的说明来操作的，docker-compose 文件也是master下的

**Comment by RivenNero** [comment]
> 可以详细说一下吗，目前就是按master分支下的说明来操作的，docker-compose 文件也是master下的。谢谢

把 `:latest` 改成 `:master`

**Comment by anzksdk** [comment]
> > 可以详细说一下吗，目前就是按master分支下的说明来操作的，docker-compose 文件也是master下的。谢谢
> 
> 把 `:latest` 改成 `:master`

error response from daemon: Head "https://ghcr.io/v2/zlib-searcher/zlib-searcher/manifests/master": unauthorized
一样也是unauthorized

**Comment by zu1k** [comment]
Sorry for that, fix it.

**Comment by ZevaXu** [comment]
OK，刚刚把docker-compose.yml文件里的镜像改成ghcr.io/zlib-searcher/zlib-searcher:master就好了，谢谢。
不过默认的ipfs网关地址好像都不太好使，换了一个ipfs.fleek.co的可以正常下载。
