### ISSUE TITLE
Docker pull prompted “manifest unknown”

### ISSUE THREAD

**Issue by TomBener** [zlib-searcher/zlib-searcher#43]
I deployed the project on Docker with the command: `docker-compose up -d`, but it warns `manifest unknown`.

I have found the version in `docker-compose.yml` is `latest`:

https://github.com/zlib-searcher/zlib-searcher/blob/73f0ae5b6e4ac8dcae2a5836363c22b418373e64/docker-compose.yml#L5

However, the docker command is `master` in the [package container](https://github.com/zlib-searcher/zlib-searcher/pkgs/container/zlib-searcher):

```shell
docker pull ghcr.io/zlib-searcher/zlib-searcher:master
```

Changing `latest` to `master` worked for me. If it’s a general issue, please fix it.

**Comment by zu1k** [comment]
This is due to releases loss due to repository migration, the problem will be solved automatically when a new version is released

**Comment by missuo** [comment]
```
root@missuo:~/zlib-searcher# docker-compose up -d
Creating network "zlib-searcher_default" with the default driver
Pulling zlib (ghcr.io/zlib-searcher/zlib-searcher:latest)...
ERROR: manifest unknown
```
