### ISSUE TITLE
ERROR: manifest unknown

### ISSUE THREAD

**Issue by xinmans** [zlib-searcher/zlib-searcher#52]
git clone https://github.com/zlib-searcher/zlib-searcher.git && cd zlib-searcher
wget https://github.com/zlib-searcher/zlib-searcher/releases/download/0.6.0/index_0.6.zip && unzip index_0.6.zip
docker-compose up -d
Now zlib-searcher it will listen to 0.0.0.0:7070.

After run above command, encounter error as below, what happened?
 
sudo docker-compose up -d
Pulling zlib (ghcr.io/zlib-searcher/zlib-searcher:latest)...
ERROR: manifest unknown

**Comment by CooperHash** [comment]
me too

**Comment by CooperHash** [comment]
go to zlib-search dir change docker.compose.yml，change this `image: ghcr.io/zlib-searcher/zlib-searcher:master`，lastest -> master

**Comment by FDUZS** [comment]
https://github.com/zlib-searcher/zlib-searcher/issues/43#issue-1507506341
