### ISSUE TITLE
https://zlib.zu1k.com/ Error code 1020

### ISSUE THREAD

**Issue by NukeManDan** [zlib-searcher/zlib-searcher#57]
I got an error when visiting zlib.zu1k.com/. Error code: 1020 Ray ID: 7819e5389c898e4e Country: IL Data center: tlv03 IP: 85.65.187.66 Timestamp: 2022-12-30 09:54:40 UTC

https://news.ycombinator.com/item?id=34176479#34186984

**Comment by NukeManDan** [comment]
@zu1k it's still down.

**Comment by NukeManDan** [comment]
@zu1k it's still down.

**Comment by zu1k** [comment]
I'm very sorry, the demo instance is permanently offline.
