### ISSUE TITLE
Book download feature no longer available

### ISSUE THREAD

**Issue by baptiste313** [zlib-searcher/zlib-searcher#58]
Hi there,

I noticed that it is no longer possible to directly download books using the buttons on the tool. Is this a intentional change? If so, I think it is unfortunate as it removes a lot of the convenience and appeal of the tool. Could you please let me know the reason for this change and if there are any plans to restore the ability to directly download books?
Thank you for your time.

**Comment by zu1k** [comment]
Yes, we removed all the built-in ipfs gateway addresses, you can add them in the settings if you need. #38
