### ISSUE TITLE
command not found: zlib-searcher

### ISSUE THREAD

**Issue by socekin** [zlib-searcher/zlib-searcher#59]
Compile according to the build instructions, but the zlib-searcher command does not work, how should I build the index file? thanks

![ScreenShot 2023-01-02 at 12 05 39@2x](https://user-images.githubusercontent.com/874961/210194422-27c740fa-4e7f-46ea-bec3-3a1799c1bc90.png)

**Comment by zu1k** [comment]
correct your path
